### ISSUE TITLE
Can open brd/sch files

### ISSUE THREAD

**Issue by rommax-jude** [mgerstgrasser/tc4plus-coffee-roaster-shield#1]
Hi mgerstgrasser, 

downloaded board design files in brd/sch, but cadence could not open them and reminded file was corrupted. could you update files or indicate what software may open them. thanks!

**Comment by mgerstgrasser** [comment]
Hi rommax-jude, the files were created in EAGLE and should open without issue there.

**Comment by rommax-jude** [comment]
Hi Mgerstgrasser,
thank you very much, i used wrong software (Cedence) to open files. problem already gone.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mgerstgrasser"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 晚上8:49
收件人:&nbsp;"mgerstgrasser/tc4plus-coffee-roaster-shield"<tc4plus-coffee-roaster-shield@noreply.github.com&gt;;
抄送:&nbsp;"青蛙&amp;天鹅"<50833085@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mgerstgrasser/tc4plus-coffee-roaster-shield] Can open brd/sch files (#1)





 
Hi rommax-jude, the files were created in EAGLE and should open without issue there.
